// Generated by scripts/trace-logo.mjs from assets/logo-source.png. Do not edit by hand.
export const LOGO_VIEWBOX = "7 11 1629 1696";
export const LOGO_WIDTH = 1644;
export const LOGO_HEIGHT = 1713;
// Ring terminals of the mark, in viewBox units.
export const LOGO_NODES: Array<{ x: number; y: number; r: number }> = [{"x":823.6,"y":139.4,"r":58},{"x":557.2,"y":367,"r":58.5},{"x":1088.1,"y":368.7,"r":59.5},{"x":227.3,"y":513.3,"r":57.5},{"x":1414.1,"y":516.4,"r":56.5},{"x":1507.9,"y":879,"r":58},{"x":134.8,"y":879.9,"r":57},{"x":1424.9,"y":1245.3,"r":59},{"x":219,"y":1246.5,"r":60.5},{"x":559.4,"y":1392,"r":59},{"x":1089.9,"y":1392.4,"r":60.5},{"x":824.1,"y":1578.6,"r":59}];
